services:

  postgres:
    image: postgres:latest
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - backend

  core:
    build: ./core
    env_file:
      - .env.prod
    container_name: core
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '8000:8000' 
    depends_on:
      - postgres
      - nginx
    networks:
      - backend

  analytics:
    build: ./analytics
    env_file:
      - .env.prod
    container_name: analytics
    command: gunicorn analytics.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres
      - nginx
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
