services:

  postgres:
    image: postgres:latest
    env_file:
      - .env.dev
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    restart: unless-stopped
    networks:
      - backend

  core:
    build: ./core
    env_file:
      - .env.dev
    container_name: core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/code
    ports:
      - '8000:8000' # только core доступен снаружи
    depends_on:
      - postgres
      - nginx
    networks:
      - backend

  analytics: # доступен изнутри контейнера по http://analytics:8000
    build: ./analytics
    env_file:
      - .env.dev
    container_name: analytics
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./analytics:/code
    depends_on:
      - postgres
      - nginx
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
